### ISSUE TITLE
Flow.cpp:170:10 compilation error

### ISSUE THREAD

**Issue by yjlintw** [kylemcdonald/ofxCv#196] opened 2016-08-10 16:03 UTC
While I try to compile ofxCv with another project: 
https://github.com/genekogan/ofxKinectProjectorToolkit

It shows the following error:

```
../../../addons/ofxCv/libs/ofxCv/src/Flow.cpp:170:10: error: no viable conversion from returned value of type 'vector<glm::tvec3<float,glm::precision::highp>>' to function return type 'vector<ofPoint>'

return poly.getVertices();
```

**Comment by yjlintw** [comment] 2016-08-10 16:40
The issue is gone if I use openframeowrks 0.9.3 on the website, instead of the master branch on github.

**Comment by frauzufall** [comment] 2016-08-15 09:08
Same problem here with the current master branch of OF.

**Comment by c1mike** [comment] 2016-09-09 23:51
i am also having trouble building the ofxCv examples against the github master branch.

i looked at the history for ofPolyline.h and i suspect the issue is the following commit that changes out ofVec3f/ofPoint for glm::vec3 across much of open frameworks:
https://github.com/openframeworks/openFrameworks/commit/82ffacaa5e965433834062d2f52e44b282901aba

i think the solution is to rewrite ofxCv to use this new convention when converting?

**Comment by philetus** [comment] 2016-09-12 20:54
i think i fixed the problem, it looks like the transition to the new glm vector format for points missed a few things, pull request here: https://github.com/kylemcdonald/ofxCv/pull/200

**Comment by Daandelange** [comment] 2016-09-16 12:40
For the information: @bakercp also has a PR preparing the move: https://github.com/kylemcdonald/ofxCv/pull/197.
@kylemcdonald could it be an idea to add a 0.9.4+ branch in openCV to keep compatibility with of:master ?

**Comment by kylemcdonald** [comment] 2017-02-08 08:21
This should be fixed now that #197 is merged.

**Closed by kylemcdonald** 2017-02-08 08:21 UTC

**Comment by hejiangda** [comment] 2017-02-11 16:41
I still have this problem

**Comment by hejiangda** [comment] 2017-02-11 16:45
/home/happy/opt/of/of_v0.9.8_linux64_release/addons/ofxCv/libs/ofxCv/src/Wrappers.cpp:92: error: ‘glm’ has not been declared
  void fitLine(const ofPolyline& polyline, glm::vec2& point, glm::vec2& direction) {
                                           ^

**Comment by hejiangda** [comment] 2017-02-11 17:15
after using ofxcv stable the problem has gone

**Comment by drscotthawley** [comment] 2018-03-13 05:53
I am getting this error in ofxCv stable.  Flow.cpp line 170.

/Users/myusername/Downloads/of_v0.9.8_ios_release/addons/ofxCv/libs/ofxCv/src/Flow.cpp:170:10: No viable conversion from returned value of type 'vector<ofPoint>' to function return type 'vector<glm::vec3>'
